baseurl: "/ii02802/task_03"
url: "https://threenebula23.github.io/OTIS-2025"
title: Документация лабораторной работы №3 — ПИД-регулятор
description: API-документация, сгенерированная Doxygen + Moxygen
theme: null

plugins:
  - jekyll-relative-links

exclude:
  - Gemfile
  - Gemfile.lock

include:
  - assets
